//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverCurrentLocation
    {
        public int DriverId { get; set; }
        public double Latitude { get; set; }
        public double Longtitude { get; set; }
        public System.TimeSpan VehicleTime { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
