//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    
    public partial class DriverTrackList_Get3_Result1
    {
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> r { get; set; }
        public Nullable<int> INTtt { get; set; }
    }
}
