//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    
    public partial class DriverTrackList_Get3_Result3
    {
        public int dt { get; set; }
        public int r { get; set; }
        public int INTtt { get; set; }
    }
}
