//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.DriverLocations = new HashSet<DriverLocation>();
            this.OrderCourierChanges = new HashSet<OrderCourierChanx>();
            this.Orders = new HashSet<Order>();
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int DriverId { get; set; }
        public string DriverName { get; set; }
        public string PhoneNum { get; set; }
        public string LicenceNum { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNum { get; set; }
        public string PassportGivenBy { get; set; }
        public Nullable<System.DateTime> PassportGivenDate { get; set; }
        public string PassportGivenDivision { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsRead { get; set; }
    
        public virtual ICollection<DriverLocation> DriverLocations { get; set; }
        public virtual ICollection<OrderCourierChanx> OrderCourierChanges { get; set; }
        public virtual DriverCurrentLocation DriverCurrentLocation { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
