//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GPEntities : DbContext
    {
        public GPEntities()
            : base("name=GPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GPUser> GPUsers { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<CurrentLocation> CurrentLocations { get; set; }
        public virtual DbSet<DriverLocation> DriverLocations { get; set; }
        public virtual DbSet<OrderCourierChanx> OrderCourierChanges { get; set; }
        public virtual DbSet<OrderStatusChanx> OrderStatusChanges { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverCurrentLocation> DriverCurrentLocations { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    
        public virtual ObjectResult<OrderStatistics_Get_Result> OrderStatistics_Get(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderStatistics_Get_Result>("OrderStatistics_Get", order_idParameter);
        }
    
        public virtual ObjectResult<OrderStatistics_Get1_Result> OrderStatistics_Get1(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderStatistics_Get1_Result>("OrderStatistics_Get1", order_idParameter);
        }
    
        public virtual ObjectResult<OrderStatistics_Get2_Result> OrderStatistics_Get2(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderStatistics_Get2_Result>("OrderStatistics_Get2", order_idParameter);
        }
    
        public virtual ObjectResult<DriverTrackList_Get_Result1> DriverTrackList_Get(string dt2, Nullable<int> r, Nullable<int> driverId)
        {
            var dt2Parameter = dt2 != null ?
                new ObjectParameter("dt2", dt2) :
                new ObjectParameter("dt2", typeof(string));
    
            var rParameter = r.HasValue ?
                new ObjectParameter("R", r) :
                new ObjectParameter("R", typeof(int));
    
            var driverIdParameter = driverId.HasValue ?
                new ObjectParameter("driverId", driverId) :
                new ObjectParameter("driverId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DriverTrackList_Get_Result1>("DriverTrackList_Get", dt2Parameter, rParameter, driverIdParameter);
        }
    }
}
