//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderCourierChanges = new HashSet<OrderCourierChanx>();
            this.OrderStatusChanges = new HashSet<OrderStatusChanx>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<int> DeliveryDriverId { get; set; }
        public Nullable<System.DateTime> DeliveredDt { get; set; }
        public string DeliveryAdress { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public string City { get; set; }
        public string Comment { get; set; }
        public int OrderStatusId { get; set; }
        public string CustomerName { get; set; }
        public string GoodsList { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsRead { get; set; }
    
        public virtual ICollection<OrderCourierChanx> OrderCourierChanges { get; set; }
        public virtual ICollection<OrderStatusChanx> OrderStatusChanges { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
