//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatu
    {
        public OrderStatu()
        {
            this.OrderStatusChanges = new HashSet<OrderStatusChanx>();
            this.Orders = new HashSet<Order>();
        }
    
        public int OrderStatusId { get; set; }
        public string OrderStatusName { get; set; }
        public System.DateTime LastUpdatedDt { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<OrderStatusChanx> OrderStatusChanges { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
