//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPConsumer.GPOrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class OrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeliveredDtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryDriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryDriverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GoodsListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LongtitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateDtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDt {
            get {
                return this.CreatedDtField;
            }
            set {
                if ((this.CreatedDtField.Equals(value) != true)) {
                    this.CreatedDtField = value;
                    this.RaisePropertyChanged("CreatedDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeliveredDt {
            get {
                return this.DeliveredDtField;
            }
            set {
                if ((this.DeliveredDtField.Equals(value) != true)) {
                    this.DeliveredDtField = value;
                    this.RaisePropertyChanged("DeliveredDt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryAdress {
            get {
                return this.DeliveryAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAdressField, value) != true)) {
                    this.DeliveryAdressField = value;
                    this.RaisePropertyChanged("DeliveryAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryDriverId {
            get {
                return this.DeliveryDriverIdField;
            }
            set {
                if ((this.DeliveryDriverIdField.Equals(value) != true)) {
                    this.DeliveryDriverIdField = value;
                    this.RaisePropertyChanged("DeliveryDriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryDriverName {
            get {
                return this.DeliveryDriverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryDriverNameField, value) != true)) {
                    this.DeliveryDriverNameField = value;
                    this.RaisePropertyChanged("DeliveryDriverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GoodsList {
            get {
                return this.GoodsListField;
            }
            set {
                if ((object.ReferenceEquals(this.GoodsListField, value) != true)) {
                    this.GoodsListField = value;
                    this.RaisePropertyChanged("GoodsList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderStatusId {
            get {
                return this.OrderStatusIdField;
            }
            set {
                if ((this.OrderStatusIdField.Equals(value) != true)) {
                    this.OrderStatusIdField = value;
                    this.RaisePropertyChanged("OrderStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderStatusName {
            get {
                return this.OrderStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusNameField, value) != true)) {
                    this.OrderStatusNameField = value;
                    this.RaisePropertyChanged("OrderStatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalCost {
            get {
                return this.TotalCostField;
            }
            set {
                if ((this.TotalCostField.Equals(value) != true)) {
                    this.TotalCostField = value;
                    this.RaisePropertyChanged("TotalCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDt {
            get {
                return this.UpdateDtField;
            }
            set {
                if ((this.UpdateDtField.Equals(value) != true)) {
                    this.UpdateDtField = value;
                    this.RaisePropertyChanged("UpdateDt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverCurrentLocationDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class DriverCurrentLocationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongtitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan VehicleTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((this.DriverIdField.Equals(value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverName {
            get {
                return this.DriverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverNameField, value) != true)) {
                    this.DriverNameField = value;
                    this.RaisePropertyChanged("DriverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan VehicleTime {
            get {
                return this.VehicleTimeField;
            }
            set {
                if ((this.VehicleTimeField.Equals(value) != true)) {
                    this.VehicleTimeField = value;
                    this.RaisePropertyChanged("VehicleTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrentLocationDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class CurrentLocationDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongtitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatusDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class OrderStatusDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatusId {
            get {
                return this.OrderStatusIdField;
            }
            set {
                if ((this.OrderStatusIdField.Equals(value) != true)) {
                    this.OrderStatusIdField = value;
                    this.RaisePropertyChanged("OrderStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderStatusName {
            get {
                return this.OrderStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusNameField, value) != true)) {
                    this.OrderStatusNameField = value;
                    this.RaisePropertyChanged("OrderStatusName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class DriverDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenceNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportGivenByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PassportGivenDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportGivenDivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassportSeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((this.DriverIdField.Equals(value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverName {
            get {
                return this.DriverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverNameField, value) != true)) {
                    this.DriverNameField = value;
                    this.RaisePropertyChanged("DriverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenceNum {
            get {
                return this.LicenceNumField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenceNumField, value) != true)) {
                    this.LicenceNumField = value;
                    this.RaisePropertyChanged("LicenceNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportGivenBy {
            get {
                return this.PassportGivenByField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportGivenByField, value) != true)) {
                    this.PassportGivenByField = value;
                    this.RaisePropertyChanged("PassportGivenBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PassportGivenDate {
            get {
                return this.PassportGivenDateField;
            }
            set {
                if ((this.PassportGivenDateField.Equals(value) != true)) {
                    this.PassportGivenDateField = value;
                    this.RaisePropertyChanged("PassportGivenDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportGivenDivision {
            get {
                return this.PassportGivenDivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportGivenDivisionField, value) != true)) {
                    this.PassportGivenDivisionField = value;
                    this.RaisePropertyChanged("PassportGivenDivision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportNum {
            get {
                return this.PassportNumField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportNumField, value) != true)) {
                    this.PassportNumField = value;
                    this.RaisePropertyChanged("PassportNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassportSeries {
            get {
                return this.PassportSeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.PassportSeriesField, value) != true)) {
                    this.PassportSeriesField = value;
                    this.RaisePropertyChanged("PassportSeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNum {
            get {
                return this.PhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumField, value) != true)) {
                    this.PhoneNumField = value;
                    this.RaisePropertyChanged("PhoneNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class VehicleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LenghtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicencePlateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VehicleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VehicleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((this.DriverIdField.Equals(value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Lenght {
            get {
                return this.LenghtField;
            }
            set {
                if ((this.LenghtField.Equals(value) != true)) {
                    this.LenghtField = value;
                    this.RaisePropertyChanged("Lenght");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicencePlate {
            get {
                return this.LicencePlateField;
            }
            set {
                if ((object.ReferenceEquals(this.LicencePlateField, value) != true)) {
                    this.LicencePlateField = value;
                    this.RaisePropertyChanged("LicencePlate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleId {
            get {
                return this.VehicleIdField;
            }
            set {
                if ((this.VehicleIdField.Equals(value) != true)) {
                    this.VehicleIdField = value;
                    this.RaisePropertyChanged("VehicleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleName {
            get {
                return this.VehicleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VehicleNameField, value) != true)) {
                    this.VehicleNameField = value;
                    this.RaisePropertyChanged("VehicleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class OrderStatDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descr {
            get {
                return this.descrField;
            }
            set {
                if ((object.ReferenceEquals(this.descrField, value) != true)) {
                    this.descrField = value;
                    this.RaisePropertyChanged("descr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dt {
            get {
                return this.dtField;
            }
            set {
                if ((this.dtField.Equals(value) != true)) {
                    this.dtField = value;
                    this.RaisePropertyChanged("dt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverStatisticsDTO", Namespace="http://schemas.datacontract.org/2004/07/GPLib.DTO")]
    [System.SerializableAttribute()]
    public partial class DriverStatisticsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BearingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DriverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongtitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RowIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Bearing {
            get {
                return this.BearingField;
            }
            set {
                if ((this.BearingField.Equals(value) != true)) {
                    this.BearingField = value;
                    this.RaisePropertyChanged("Bearing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((this.DriverIdField.Equals(value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RowId {
            get {
                return this.RowIdField;
            }
            set {
                if ((this.RowIdField.Equals(value) != true)) {
                    this.RowIdField = value;
                    this.RaisePropertyChanged("RowId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GPOrderServiceReference.IGPOrder")]
    public interface IGPOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/AddOrder", ReplyAction="http://tempuri.org/IGPOrder/AddOrderResponse")]
        GPConsumer.GPOrderServiceReference.OrderDTO AddOrder(int orderId, System.DateTime createdDt, string deliveryAdress, double latitude, double longtitude, string city, string comment, string customerName, string goodsList, string phone, decimal totalCost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetAllOrders", ReplyAction="http://tempuri.org/IGPOrder/GetAllOrdersResponse")]
        GPConsumer.GPOrderServiceReference.OrderDTO[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetCurrentLocations", ReplyAction="http://tempuri.org/IGPOrder/GetCurrentLocationsResponse")]
        GPConsumer.GPOrderServiceReference.DriverCurrentLocationDTO[] GetCurrentLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetCurrentLocation", ReplyAction="http://tempuri.org/IGPOrder/GetCurrentLocationResponse")]
        GPConsumer.GPOrderServiceReference.CurrentLocationDTO GetCurrentLocation(int locationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/SetCurrentLocation", ReplyAction="http://tempuri.org/IGPOrder/SetCurrentLocationResponse")]
        void SetCurrentLocation(int locationId, double latitude, double longtitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetNewOrders", ReplyAction="http://tempuri.org/IGPOrder/GetNewOrdersResponse")]
        GPConsumer.GPOrderServiceReference.OrderDTO[] GetNewOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/UpdateDriverLocation", ReplyAction="http://tempuri.org/IGPOrder/UpdateDriverLocationResponse")]
        void UpdateDriverLocation(int vehicleId, double lat, double lng, System.TimeSpan time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetOrderStatusesList", ReplyAction="http://tempuri.org/IGPOrder/GetOrderStatusesListResponse")]
        GPConsumer.GPOrderServiceReference.OrderStatusDTO[] GetOrderStatusesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/SetOrderDeliveryDriverId", ReplyAction="http://tempuri.org/IGPOrder/SetOrderDeliveryDriverIdResponse")]
        void SetOrderDeliveryDriverId(int orderId, System.Nullable<int> deliveryDriverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/UpdateOrderStatus", ReplyAction="http://tempuri.org/IGPOrder/UpdateOrderStatusResponse")]
        void UpdateOrderStatus(int orderId, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetCurrentLocationsByDriverIdDate", ReplyAction="http://tempuri.org/IGPOrder/GetCurrentLocationsByDriverIdDateResponse")]
        GPConsumer.GPOrderServiceReference.DriverCurrentLocationDTO[] GetCurrentLocationsByDriverIdDate(int driverId, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/CreateOrderStatus", ReplyAction="http://tempuri.org/IGPOrder/CreateOrderStatusResponse")]
        System.Nullable<int> CreateOrderStatus(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/DeleteOrderStatus", ReplyAction="http://tempuri.org/IGPOrder/DeleteOrderStatusResponse")]
        void DeleteOrderStatus(int orderStatusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/AddDriver", ReplyAction="http://tempuri.org/IGPOrder/AddDriverResponse")]
        GPConsumer.GPOrderServiceReference.DriverDTO AddDriver(string driverName, string email, string licenceNum, string notes, string passportGivenBy, System.DateTime passportGivenDate, string passportGivenDivision, string passportNum, string passportSeries, string phoneNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetAllDrivers", ReplyAction="http://tempuri.org/IGPOrder/GetAllDriversResponse")]
        GPConsumer.GPOrderServiceReference.DriverDTO[] GetAllDrivers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/UpdateDriver", ReplyAction="http://tempuri.org/IGPOrder/UpdateDriverResponse")]
        GPConsumer.GPOrderServiceReference.DriverDTO UpdateDriver(int driverId, string driverName, string email, string licenceNum, string notes, string passportGivenBy, System.DateTime passportGivenDate, string passportGivenDivision, string passportNum, string passportSeries, string phoneNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/DeleteDriver", ReplyAction="http://tempuri.org/IGPOrder/DeleteDriverResponse")]
        void DeleteDriver(int driverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetNewDrivers", ReplyAction="http://tempuri.org/IGPOrder/GetNewDriversResponse")]
        GPConsumer.GPOrderServiceReference.DriverDTO[] GetNewDrivers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetAllVehicles", ReplyAction="http://tempuri.org/IGPOrder/GetAllVehiclesResponse")]
        GPConsumer.GPOrderServiceReference.VehicleDTO[] GetAllVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/AddVehicle", ReplyAction="http://tempuri.org/IGPOrder/AddVehicleResponse")]
        GPConsumer.GPOrderServiceReference.VehicleDTO AddVehicle(int driverId, string brand, string licencePlate, decimal length, decimal width, decimal height, decimal capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/DeleteVehicle", ReplyAction="http://tempuri.org/IGPOrder/DeleteVehicleResponse")]
        void DeleteVehicle(int vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetNewVehicles", ReplyAction="http://tempuri.org/IGPOrder/GetNewVehiclesResponse")]
        GPConsumer.GPOrderServiceReference.VehicleDTO[] GetNewVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetOrderStatistics", ReplyAction="http://tempuri.org/IGPOrder/GetOrderStatisticsResponse")]
        GPConsumer.GPOrderServiceReference.OrderStatDTO[] GetOrderStatistics(int order_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/GetDriverStatisticsHistory", ReplyAction="http://tempuri.org/IGPOrder/GetDriverStatisticsHistoryResponse")]
        GPConsumer.GPOrderServiceReference.DriverStatisticsDTO[] GetDriverStatisticsHistory(System.DateTime dt, int radius, int driverId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/Login", ReplyAction="http://tempuri.org/IGPOrder/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGPOrder/Test", ReplyAction="http://tempuri.org/IGPOrder/TestResponse")]
        void Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGPOrderChannel : GPConsumer.GPOrderServiceReference.IGPOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GPOrderClient : System.ServiceModel.ClientBase<GPConsumer.GPOrderServiceReference.IGPOrder>, GPConsumer.GPOrderServiceReference.IGPOrder {
        
        public GPOrderClient() {
        }
        
        public GPOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GPOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GPOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GPConsumer.GPOrderServiceReference.OrderDTO AddOrder(int orderId, System.DateTime createdDt, string deliveryAdress, double latitude, double longtitude, string city, string comment, string customerName, string goodsList, string phone, decimal totalCost) {
            return base.Channel.AddOrder(orderId, createdDt, deliveryAdress, latitude, longtitude, city, comment, customerName, goodsList, phone, totalCost);
        }
        
        public GPConsumer.GPOrderServiceReference.OrderDTO[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public GPConsumer.GPOrderServiceReference.DriverCurrentLocationDTO[] GetCurrentLocations() {
            return base.Channel.GetCurrentLocations();
        }
        
        public GPConsumer.GPOrderServiceReference.CurrentLocationDTO GetCurrentLocation(int locationId) {
            return base.Channel.GetCurrentLocation(locationId);
        }
        
        public void SetCurrentLocation(int locationId, double latitude, double longtitude) {
            base.Channel.SetCurrentLocation(locationId, latitude, longtitude);
        }
        
        public GPConsumer.GPOrderServiceReference.OrderDTO[] GetNewOrders() {
            return base.Channel.GetNewOrders();
        }
        
        public void UpdateDriverLocation(int vehicleId, double lat, double lng, System.TimeSpan time) {
            base.Channel.UpdateDriverLocation(vehicleId, lat, lng, time);
        }
        
        public GPConsumer.GPOrderServiceReference.OrderStatusDTO[] GetOrderStatusesList() {
            return base.Channel.GetOrderStatusesList();
        }
        
        public void SetOrderDeliveryDriverId(int orderId, System.Nullable<int> deliveryDriverId) {
            base.Channel.SetOrderDeliveryDriverId(orderId, deliveryDriverId);
        }
        
        public void UpdateOrderStatus(int orderId, int statusId) {
            base.Channel.UpdateOrderStatus(orderId, statusId);
        }
        
        public GPConsumer.GPOrderServiceReference.DriverCurrentLocationDTO[] GetCurrentLocationsByDriverIdDate(int driverId, System.DateTime date) {
            return base.Channel.GetCurrentLocationsByDriverIdDate(driverId, date);
        }
        
        public System.Nullable<int> CreateOrderStatus(string name) {
            return base.Channel.CreateOrderStatus(name);
        }
        
        public void DeleteOrderStatus(int orderStatusId) {
            base.Channel.DeleteOrderStatus(orderStatusId);
        }
        
        public GPConsumer.GPOrderServiceReference.DriverDTO AddDriver(string driverName, string email, string licenceNum, string notes, string passportGivenBy, System.DateTime passportGivenDate, string passportGivenDivision, string passportNum, string passportSeries, string phoneNum) {
            return base.Channel.AddDriver(driverName, email, licenceNum, notes, passportGivenBy, passportGivenDate, passportGivenDivision, passportNum, passportSeries, phoneNum);
        }
        
        public GPConsumer.GPOrderServiceReference.DriverDTO[] GetAllDrivers() {
            return base.Channel.GetAllDrivers();
        }
        
        public GPConsumer.GPOrderServiceReference.DriverDTO UpdateDriver(int driverId, string driverName, string email, string licenceNum, string notes, string passportGivenBy, System.DateTime passportGivenDate, string passportGivenDivision, string passportNum, string passportSeries, string phoneNum) {
            return base.Channel.UpdateDriver(driverId, driverName, email, licenceNum, notes, passportGivenBy, passportGivenDate, passportGivenDivision, passportNum, passportSeries, phoneNum);
        }
        
        public void DeleteDriver(int driverId) {
            base.Channel.DeleteDriver(driverId);
        }
        
        public GPConsumer.GPOrderServiceReference.DriverDTO[] GetNewDrivers() {
            return base.Channel.GetNewDrivers();
        }
        
        public GPConsumer.GPOrderServiceReference.VehicleDTO[] GetAllVehicles() {
            return base.Channel.GetAllVehicles();
        }
        
        public GPConsumer.GPOrderServiceReference.VehicleDTO AddVehicle(int driverId, string brand, string licencePlate, decimal length, decimal width, decimal height, decimal capacity) {
            return base.Channel.AddVehicle(driverId, brand, licencePlate, length, width, height, capacity);
        }
        
        public void DeleteVehicle(int vehicleId) {
            base.Channel.DeleteVehicle(vehicleId);
        }
        
        public GPConsumer.GPOrderServiceReference.VehicleDTO[] GetNewVehicles() {
            return base.Channel.GetNewVehicles();
        }
        
        public GPConsumer.GPOrderServiceReference.OrderStatDTO[] GetOrderStatistics(int order_id) {
            return base.Channel.GetOrderStatistics(order_id);
        }
        
        public GPConsumer.GPOrderServiceReference.DriverStatisticsDTO[] GetDriverStatisticsHistory(System.DateTime dt, int radius, int driverId) {
            return base.Channel.GetDriverStatisticsHistory(dt, radius, driverId);
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public void Test() {
            base.Channel.Test();
        }
    }
}
